from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd


# ============================================================
# 0. Path settings
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[1]

OUTPUT_DIR = BASE_DIR / "outputs"
FIGURE_DIR = OUTPUT_DIR / "figures"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FIGURE_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# 1. Load outputs generated by earlier stages
# ============================================================

yearly_sales_path = OUTPUT_DIR / "yearly_summer_sales.csv"
monthly_sales_path = OUTPUT_DIR / "monthly_summer_sales.csv"
holiday_sales_path = OUTPUT_DIR / "holiday_sales_summary.csv"
store_type_sales_path = OUTPUT_DIR / "store_type_sales_summary.csv"
region_sales_path = OUTPUT_DIR / "region_sales_summary.csv"
department_sales_path = OUTPUT_DIR / "department_sales_summary.csv"
rolling_summary_path = OUTPUT_DIR / "rolling_origin_summary.csv"
rolling_winners_path = OUTPUT_DIR / "rolling_origin_fold_winners.csv"
feature_importance_path = OUTPUT_DIR / "xgboost_feature_importance.csv"

required_paths = [
    yearly_sales_path,
    monthly_sales_path,
    holiday_sales_path,
    store_type_sales_path,
    region_sales_path,
    department_sales_path,
    rolling_summary_path,
    rolling_winners_path,
    feature_importance_path,
]

missing_paths = [
    path
    for path in required_paths
    if not path.exists()
]

if missing_paths:
    formatted_missing = "\n".join(
        f"- {path}"
        for path in missing_paths
    )
    raise FileNotFoundError(
        "Required project outputs are missing:\n"
        f"{formatted_missing}"
    )

yearly_sales = pd.read_csv(yearly_sales_path)
monthly_sales = pd.read_csv(monthly_sales_path)
holiday_sales = pd.read_csv(holiday_sales_path)
store_type_sales = pd.read_csv(store_type_sales_path)
region_sales = pd.read_csv(region_sales_path)
department_sales = pd.read_csv(department_sales_path)
rolling_summary = pd.read_csv(rolling_summary_path)
rolling_winners = pd.read_csv(rolling_winners_path)
feature_importance = pd.read_csv(feature_importance_path)


# ============================================================
# 2. Calculate business and model metrics
# ============================================================

# 2.1 Summer sales growth
yearly_sales = yearly_sales.sort_values("year")

first_year = int(yearly_sales.iloc[0]["year"])
last_year = int(yearly_sales.iloc[-1]["year"])

first_year_sales = yearly_sales.iloc[0]["total_summer_sales"]
last_year_sales = yearly_sales.iloc[-1]["total_summer_sales"]

summer_growth = (
    (last_year_sales - first_year_sales)
    / first_year_sales
    * 100
)


# 2.2 Highest-sales summer month
monthly_sales = monthly_sales.sort_values(
    "total_sales",
    ascending=False,
)

best_month_name = monthly_sales.iloc[0]["month_name"]
best_month_sales = monthly_sales.iloc[0]["total_sales"]


# 2.3 Holiday lift
holiday_lift = None

if "holiday_type" in holiday_sales.columns:
    holiday_pivot = holiday_sales.set_index(
        "holiday_type"
    )["avg_weekly_sales"]

    required_holiday_labels = {
        "Holiday",
        "Non-Holiday",
    }

    if required_holiday_labels.issubset(
        holiday_pivot.index
    ):
        holiday_sales_avg = holiday_pivot["Holiday"]
        non_holiday_sales_avg = holiday_pivot[
            "Non-Holiday"
        ]

        holiday_lift = (
            (holiday_sales_avg - non_holiday_sales_avg)
            / non_holiday_sales_avg
            * 100
        )


# 2.4 Store-type contribution
store_type_sales = store_type_sales.sort_values(
    "total_sales",
    ascending=False,
)

top_store_type = store_type_sales.iloc[0]["store_type"]
top_store_type_sales = store_type_sales.iloc[0][
    "total_sales"
]


# 2.5 Regional contribution
region_sales = region_sales.sort_values(
    "total_sales",
    ascending=False,
)

top_region = region_sales.iloc[0]["region"]
top_region_sales = region_sales.iloc[0][
    "total_sales"
]


# 2.6 Top departments
department_sales = department_sales.sort_values(
    "total_sales",
    ascending=False,
)

top_departments = department_sales.head(5)


# 2.7 Final model selection from rolling-origin backtesting
rolling_summary = rolling_summary.sort_values(
    ["rank", "mean_company_wape"]
).reset_index(drop=True)

best_model_row = rolling_summary.iloc[0]

best_model = best_model_row["model"]
best_mean_mape = best_model_row["mean_company_mape"]
best_mean_wape = best_model_row["mean_company_wape"]
best_median_wape = best_model_row["median_company_wape"]
best_std_wape = best_model_row["std_company_wape"]
best_min_wape = best_model_row["min_company_wape"]
best_max_wape = best_model_row["max_company_wape"]
best_mean_bias = best_model_row["mean_company_bias"]
best_mean_absolute_bias = best_model_row[
    "mean_absolute_company_bias"
]
best_fold_wins = int(best_model_row["fold_wins"])
best_total_folds = int(best_model_row["folds"])

baseline_rows = rolling_summary[
    rolling_summary["model"]
    .astype(str)
    .str.contains(
        "Rolling 4-Week",
        case=False,
        na=False,
    )
]

if baseline_rows.empty:
    baseline_mean_wape = None
    wape_reduction_over_baseline = None
else:
    baseline_mean_wape = baseline_rows.iloc[0][
        "mean_company_wape"
    ]

    wape_reduction_over_baseline = (
        (baseline_mean_wape - best_mean_wape)
        / baseline_mean_wape
        * 100
    )


# 2.8 Fold winners and XGBoost features
winning_fold_numbers = (
    rolling_winners.loc[
        rolling_winners["winning_model"] == best_model,
        "fold",
    ]
    .astype(int)
    .tolist()
)

top_features = feature_importance.head(10)


# ============================================================
# 3. Plot rolling-origin model comparison
# ============================================================

plot_model = rolling_summary.sort_values(
    "mean_company_wape",
    ascending=True,
)

fig, ax = plt.subplots(figsize=(11, 6))

ax.bar(
    plot_model["model"],
    plot_model["mean_company_wape"],
)

ax.set_title(
    "Rolling-Origin Model Comparison by Mean Company WAPE"
)

ax.set_xlabel("Model")
ax.set_ylabel("Mean Company-Level WAPE (%)")
ax.tick_params(
    axis="x",
    rotation=25,
)

ax.grid(
    axis="y",
    alpha=0.3,
)

fig.tight_layout()

model_fig_path = (
    FIGURE_DIR
    / "16_rolling_origin_model_comparison.png"
)

fig.savefig(
    model_fig_path,
    dpi=150,
)

plt.close(fig)


# ============================================================
# 4. Generate updated business recommendations
# ============================================================

recommendation_path = (
    OUTPUT_DIR
    / "business_recommendations.md"
)

lines = []

lines.append("# Business Recommendations")
lines.append("")

lines.append("## Project Context")
lines.append("")
lines.append(
    "This portfolio project uses a structured educational, "
    "synthetic, or adapted retail dataset in a hypothetical "
    "department-store business scenario. It does not claim to "
    "use confidential internal data from a real Chongqing retailer."
)
lines.append("")
lines.append(
    "The operational forecasting scenario predicts one week ahead "
    "using calendar information, store and department attributes, "
    "planned markdown variables, and leakage-safe historical sales "
    "features."
)
lines.append("")

lines.append("## Key Business Findings")
lines.append("")

lines.append(
    f"1. **Summer sales increased by approximately "
    f"{summer_growth:.2f}% from {first_year} to {last_year}.**"
)
lines.append(
    "   This indicates stronger summer demand in the latest year "
    "within the current dataset."
)
lines.append("")

lines.append(
    f"2. **{best_month_name} generated the highest total "
    "summer sales.**"
)
lines.append(
    "   Promotion, inventory, and staffing plans should place "
    "additional attention on this peak summer period."
)
lines.append("")

if holiday_lift is not None:
    lines.append(
        f"3. **Holiday weeks had approximately "
        f"{holiday_lift:.2f}% higher average weekly sales than "
        "non-holiday weeks.**"
    )
    lines.append(
        "   Holiday periods should be treated as high-demand "
        "planning windows, while the holiday definitions should "
        "be localised before real deployment."
    )
else:
    lines.append(
        "3. **Holiday impact could not be fully quantified from "
        "the available summary table.**"
    )

lines.append("")

lines.append(
    f"4. **Store Type {top_store_type} contributed the largest "
    "share of total summer sales.**"
)
lines.append(
    "   Higher-contribution store types may require greater "
    "inventory, staffing, and promotion capacity."
)
lines.append("")

lines.append(
    f"5. **The {top_region} region contributed the highest total "
    "summer sales among the available regional labels.**"
)
lines.append(
    "   Regional demand differences should be considered in "
    "resource allocation, subject to validation on real local data."
)
lines.append("")

lines.append("6. **Top-performing departments were:**")

for _, row in top_departments.iterrows():
    lines.append(
        f"   - Department {int(row['department'])}: "
        f"total summer sales = {row['total_sales']:,.0f}"
    )

lines.append("")

lines.append("## Final Model Performance")
lines.append("")
lines.append(
    "Final model selection is based on six expanding-window "
    "rolling-origin backtest folds rather than one favourable "
    "summer test period."
)
lines.append("")
lines.append(
    f"- Selected model: **{best_model}**."
)
lines.append(
    f"- Mean company-level MAPE: **{best_mean_mape:.2f}%**."
)
lines.append(
    f"- Mean company-level WAPE: **{best_mean_wape:.2f}%**."
)
lines.append(
    f"- Median company-level WAPE: **{best_median_wape:.2f}%**."
)
lines.append(
    f"- WAPE standard deviation: **{best_std_wape:.2f}**."
)
lines.append(
    f"- Best-fold WAPE: **{best_min_wape:.2f}%**."
)
lines.append(
    f"- Worst-fold WAPE: **{best_max_wape:.2f}%**."
)
lines.append(
    f"- Fold wins: **{best_fold_wins} of "
    f"{best_total_folds}**."
)
lines.append(
    f"- Mean absolute company-level forecast bias: "
    f"**{best_mean_absolute_bias:.2f}%**."
)

if winning_fold_numbers:
    formatted_folds = ", ".join(
        str(fold)
        for fold in winning_fold_numbers
    )
    lines.append(
        f"- Winning folds: **{formatted_folds}**."
    )

if (
    baseline_mean_wape is not None
    and wape_reduction_over_baseline is not None
):
    lines.append(
        f"- Rolling four-week baseline mean WAPE: "
        f"**{baseline_mean_wape:.2f}%**."
    )
    lines.append(
        f"- Mean WAPE reduction relative to the rolling baseline: "
        f"**{wape_reduction_over_baseline:.2f}%**."
    )

lines.append("")
lines.append(
    "Operational XGBoost is preferred because it achieved the "
    "lowest mean WAPE, won five of six folds, and showed the "
    "strongest cross-season stability. Random Forest remains a "
    "useful alternative because it performed best in one "
    "summer-focused fold."
)
lines.append("")

lines.append("## XGBoost Model Interpretation")
lines.append("")
lines.append(
    "The existing XGBoost feature-importance output provides an "
    "initial view of model contribution. It should not be "
    "interpreted as causal evidence."
)
lines.append("")

for _, row in top_features.iterrows():
    lines.append(f"- `{row['feature']}`")

lines.append("")
lines.append(
    "The feature-importance results suggest that store type, "
    "holiday information, historical rolling sales, store size, "
    "month, and seasonal variables contributed to prediction."
)
lines.append("")

lines.append("## Operational Recommendations")
lines.append("")

lines.append(
    "### 1. Use the forecast as a weekly planning signal"
)
lines.append(
    "Generate one-week-ahead forecasts on a fixed weekly schedule "
    "and review predicted peaks before inventory and staffing "
    "decisions are finalised."
)
lines.append("")

lines.append(
    "### 2. Prioritise peak summer and holiday planning"
)
lines.append(
    f"Because {best_month_name} and holiday periods showed stronger "
    "sales, management should prepare promotions, staffing, and "
    "inventory earlier for those periods."
)
lines.append("")

lines.append(
    "### 3. Apply differentiated resource allocation"
)
lines.append(
    f"Store Type {top_store_type}, the {top_region} region, and "
    "high-performing departments should receive targeted planning "
    "attention rather than uniform allocation."
)
lines.append("")

lines.append(
    "### 4. Monitor WAPE and forecast bias together"
)
lines.append(
    "Low WAPE measures forecast accuracy, while forecast bias "
    "helps detect persistent over- or under-planning. Both should "
    "be monitored after deployment."
)
lines.append("")

lines.append(
    "### 5. Keep a baseline challenger"
)
lines.append(
    "Continue comparing XGBoost with Random Forest and the rolling "
    "four-week baseline. A simpler model should replace the "
    "primary model if live performance deteriorates."
)
lines.append("")

lines.append(
    "### 6. Do not use company-level accuracy as a granular claim"
)
lines.append(
    "Company-level WAPE is much lower than store-department-level "
    "WAPE. Aggregate accuracy should not be presented as equally "
    "strong inventory-item or department accuracy."
)
lines.append("")

lines.append("## Limitations")
lines.append("")
lines.append(
    "- The dataset is not verified as real internal Chongqing "
    "retail data."
)
lines.append(
    "- Holiday labels and field units require local validation."
)
lines.append(
    "- Markdown variables are assumed to represent planned "
    "promotions known before the forecast week."
)
lines.append(
    "- Inventory, stockouts, competitor actions, and local events "
    "are not included."
)
lines.append(
    "- The model has not yet been tested on live future data."
)
lines.append("")

lines.append("## Interview Talking Point")
lines.append("")
lines.append(
    "This project demonstrates an end-to-end retail forecasting "
    "workflow covering business-key validation, safe multi-table "
    "merging, leakage-safe lag features, forecast-time feature "
    "auditing, baseline and statistical model comparison, and "
    "six-fold rolling-origin backtesting. Operational XGBoost "
    f"achieved a mean company-level WAPE of "
    f"{best_mean_wape:.2f}%, won {best_fold_wins} of "
    f"{best_total_folds} folds, and reduced average WAPE by "
    f"{wape_reduction_over_baseline:.2f}% relative to the rolling "
    "four-week baseline."
)

recommendation_path.write_text(
    "\n".join(lines),
    encoding="utf-8",
)


# ============================================================
# 5. Save business summary metrics
# ============================================================

summary_rows = [
    {
        "metric": "first_year",
        "value": first_year,
    },
    {
        "metric": "last_year",
        "value": last_year,
    },
    {
        "metric": "summer_sales_growth_pct",
        "value": round(summer_growth, 2),
    },
    {
        "metric": "best_summer_month",
        "value": best_month_name,
    },
    {
        "metric": "best_summer_month_sales",
        "value": round(best_month_sales, 2),
    },
    {
        "metric": "top_store_type",
        "value": top_store_type,
    },
    {
        "metric": "top_store_type_sales",
        "value": round(top_store_type_sales, 2),
    },
    {
        "metric": "top_region",
        "value": top_region,
    },
    {
        "metric": "top_region_sales",
        "value": round(top_region_sales, 2),
    },
    {
        "metric": "selected_model",
        "value": best_model,
    },
    {
        "metric": "mean_company_mape",
        "value": round(best_mean_mape, 4),
    },
    {
        "metric": "mean_company_wape",
        "value": round(best_mean_wape, 4),
    },
    {
        "metric": "median_company_wape",
        "value": round(best_median_wape, 4),
    },
    {
        "metric": "std_company_wape",
        "value": round(best_std_wape, 4),
    },
    {
        "metric": "min_company_wape",
        "value": round(best_min_wape, 4),
    },
    {
        "metric": "max_company_wape",
        "value": round(best_max_wape, 4),
    },
    {
        "metric": "mean_company_bias",
        "value": round(best_mean_bias, 4),
    },
    {
        "metric": "mean_absolute_company_bias",
        "value": round(best_mean_absolute_bias, 4),
    },
    {
        "metric": "fold_wins",
        "value": best_fold_wins,
    },
    {
        "metric": "total_folds",
        "value": best_total_folds,
    },
    {
        "metric": "rolling_baseline_mean_wape",
        "value": (
            round(baseline_mean_wape, 4)
            if baseline_mean_wape is not None
            else None
        ),
    },
    {
        "metric": "wape_reduction_over_baseline_pct",
        "value": (
            round(wape_reduction_over_baseline, 2)
            if wape_reduction_over_baseline is not None
            else None
        ),
    },
]

summary = pd.DataFrame(summary_rows)

summary_path = (
    OUTPUT_DIR
    / "business_summary_metrics.csv"
)

summary.to_csv(
    summary_path,
    index=False,
)


# ============================================================
# 6. Print completion summary
# ============================================================

print("\n========== Updated Business Summary ==========")
print(summary.to_string(index=False))

print("\nSaved updated business recommendations to:")
print(recommendation_path)

print("\nSaved updated business summary metrics to:")
print(summary_path)

print("\nSaved rolling-origin model comparison figure to:")
print(model_fig_path)

print(
    "\nBusiness recommendation generation "
    "completed successfully."
)
